pipeline {
    agent none

    stages {
        stage('Build') {
            agent any
            steps {
                echo 'Building application'
            }
        }
        stage('Test') {
            agent none
            steps {
                echo 'Testing application'
            }
        }
        stage('Deploy') {
            agent none
            steps {
                echo 'Deploying application'
            }
        }
    }
}
